Issue 8 support us pages
codersforcauses/starick pull request #75
Opened 2023-12-17 03:09 UTC by MoeBuTa

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-12-18 08:08 UTC, cjnbennett requested changes
Looks good, just a couple minor things - see the comment I made on the files, and also it looks like the PayPal button has too high a z-index and will appear on top of the navigation bar (if you scroll that far).

2023-12-18 08:08 UTC, cjnbennett commented on src/components/Services/ResourceAndToolkits/child-safe-list.tsx
> +          backgroundColor={child.backgroundColor} // Assuming order is a number
Strange comment here?

2023-12-18 15:34 UTC, MoeBuTa commented on src/components/Services/ResourceAndToolkits/child-safe-list.tsx
> +          backgroundColor={child.backgroundColor} // Assuming order is a number
fixed these two issues

2023-12-24 04:50 UTC, cjnbennett approved these changes
Lgtm

2023-12-24 07:20 UTC, merged